prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix dbo: <http://dbpedia.org/ontology/>
prefix owl: <http://www.w3.org/2002/07/owl#>

select distinct ?battle ?sameAs where {
    ?battle rdf:type dbo:MilitaryConflict .
    ?battle rdf:type dbo:Event .
    ?battle owl:sameAs ?sameAs .
}
