prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix dbp: <http://dbpedia.org/property/>


select distinct ?battle ?date_property  where {
    ?battle rdf:type dbo:MilitaryConflict .
    ?battle rdf:type dbo:Event .
    ?battle dbp:date ?date_property .
}
